### ISSUE TITLE
Model Weight Can't Be Loaded due to Git LFS load limit

### ISSUE THREAD

**Issue by takeimhk** [HRNPH/AIwaifu#24] opened 2023-04-15 15:23 UTC
when i do python main.py error appear

![image](https://user-images.githubusercontent.com/81930758/232233914-4885c6ae-1781-4024-a5e7-a2c33ad7c6ed.png)

**Comment by HRNPH** [comment] 2023-04-15 15:40
It seems that the error caused the checkpoint loading of the model which seems to be caused by an incorrect model weight
make sure you have [GITL-FS](https://git-lfs.com/) installed on your computer

**Comment by takeimhk** [comment] 2023-04-15 17:04
thanks for the help, but still error

![image](https://user-images.githubusercontent.com/81930758/232240279-74dbca7e-a8bf-4028-a97a-306091e81ae7.png)

heres the log: 
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.40.0.windows.1

$ git-lfs.exe filter-process
Error downloading object: anime_tts/1374_epochs.pth (edfb6b4): Smudge error: Error downloading anime_tts/1374_epochs.pth (edfb6b428c398fab83a85b5ae41e13cb5a9f7be12692129e8a880d4553701f7b): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response
[20230415T235953.0682821.log](https://github.com/HRNPH/AIwaifu/files/11240061/20230415T235953.0682821.log)

**Comment by takeimhk** [comment] 2023-04-15 17:23
it still the same, already install git lfs and error when doing git clone : 

![image](https://user-images.githubusercontent.com/81930758/232242445-4059fd65-8de4-44a4-a489-220060a720dc.png)

**Comment by HRNPH** [comment] 2023-04-15 17:27
ohhh it's my fault because I'm out of git LFS quota you need to download the model via this link and placed it in the folder manually then https://huggingface.co/spaces/kouenYoung/anime-tts/resolve/main/1374_epochs.pth

**Comment by HRNPH** [comment] 2023-04-15 17:56
The new version of the code now fixed the model download problem using git lfs to use wget instead
 you should try to delete the folder and clone it again [refer](f0b5b710af85ea4bada9f90a566e783be27a436d)

**Comment by HRNPH** [comment] 2023-04-15 18:00
Thx for noticing the problem please notice me if this issue was fixed so I can close this issue!

**Comment by takeimhk** [comment] 2023-04-15 19:33
awesomeeee, it works. 

you are awsome! Keeper going!

so i am just asking, what database the the AI use? the AI answer my question with veeery long text and repeating, while i use different question or text

cheers!

**Comment by HRNPH** [comment] 2023-04-16 11:00
currently, the model is the pygmalion6B which was trained on something like RPG conversation or novel stuff conversation
there's no database that model relies on to answer except the trained weight(knowledge) on the datasets that she has seen
the context of how the model will reply will pretty much depend on your history of conversation 
(currently capped at 10 lines to save memory in the test so the result is she'll not remember the old conversations at all)
I'l increase the memory to 30-40 lines, It should give better answer

**Closed** 2023-04-16 11:07 UTC
Labels: bug
